input_dir: data/raw/
output_dir: data/processed/
site_name: Canny Woods

outputs:
  write_csv: false

fallback_location:
  latitude: 50.432000
  longitude: -3.672000

devices:
  24F319046907737B:
    label: audiomoth_1
    fallback_location:
      latitude: 50.432584
      longitude: -3.672039

  24F319046907737C:
    label: audiomoth_2

chunking:
  enabled: false
  duration_s: 3.0
  overlap_s: 1.0
  write_chunk_inventory: true
  write_audio_files: true
  output_dir: data/interim/chunks
  analysis_targets:
    - bird

birdnet:
  output_dir: data/processed/birdnet
  model_version: "2.4"
  model_backend: tf
  min_confidence: 0.25
  batch_size: 1
  fmin_hz: 0.0
  fmax_hz: 15000.0
  sensitivity: 1.0
  overlap_s: 0.0
